name: Deploy to Google Cloud Functions
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - .github/workflows/deploy.yml


jobs:
    Deploy:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v1'
              with:
                    create_credentials_file: true
                    workload_identity_provider: '${{ secrets.WORKLOAD_IAM_PROVIDER }}'
                    service_account: '${{ secrets.SERVICE_ACCOUNT }}'
            - id: 'deploy'
              uses: 'google-github-actions/deploy-cloud-functions@v1'
              with:
                  name: 'gpt-generate-text'
                  runtime: 'Python 3.11'
                  entry_point: 'entry_point'
                  region: '${{ secrets.REGION }}'
                  env_vars: '${{ secrets.FN_ENV }}'
                  source_dir: 'src'
                  secret_environment_variables: '${{ secrets.FN_SECRET_ENV }}'
                  max_instances: 1
