name: Deploy to Google Cloud Functions
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - .github/workflows/deploy.yml


jobs:
    Deploy:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v1'
              with:
                  workload_identity_provider: '${{ secrets.WORKLOAD_IAM_PROVIDER }}'
                  service_account: '${{ secrets.SERVICE_ACCOUNT }}'
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'
              with:
                  version: '>= 363.0.0'
            - name: 'Deploy'
              run:
                "gcloud functions deploy gpt-generate-text \
                --runtime python38 \
                --entry_point entry_point
                --region ${{ secrets.REGION }} \
                --set-env-vars ${{ secrets.FN_ENV }} \
                --source src \
                --set-secrets ${{ secrets.FN_SECRET_ENV }} \
                --max_instances 1 \
                --service_account: ${{ secrets.RUNTIME_SERVICE_ACCOUNT_EMAIL }} \
                --trigger-event 'providers/cloud.pubsub/eventTypes/topic.publish' \
                --trigger-resource '${{ secrets.EVENT_TRIGGER_RESOURCE }}' \
                -- gen2"
